### ISSUE TITLE
loading IDM weights without VPT's lib code?

### ISSUE THREAD

**Issue by nollied** [openai/Video-Pre-Training#19]
i'm having a lot of trouble trying to get the inverse dynamics model weights to work in a separate custom torch nn module. all the custom model code is spread out through VPT's lib modules and the complexity is a bit overwhelming for me.

do you have any bare-bones loading methods for the weights? or do you think the complexity is just the nature of the beast

i'd like to basically just use IDM's latent representation (before it goes to the policy head) and add my own custom policy head to it. but doing so ruptures a lot of the functionality.

**Comment by Miffyli** [comment]
Hmm unfortunately I think the code is mostly as barebones it can get; you could remove some features that are not used and skip parts here and there, but not by much. Alternativaly you could simplify things, but our first aim was to share code asap and as close to original format as possible to avoid breaking anything.

You are right the model code itself could probably be smaller, but shaping the inputs for the model in correct way are also important: otherwise you can not use the model right.

**Comment by nollied** [comment]
@Miffyli right, so is your recommendation to copy the module code and add it to my submission?

**Comment by Miffyli** [comment]
Yes, for the BASALT competition, you should copy this code as part of your submission.

Small protip: default .gitignore templates include `lib` as one of the ignored names, which leads to the `lib` directory being ignored by default 🙃

**Comment by nollied** [comment]
@Miffyli copy that, thanks king
