### ISSUE TITLE
Question about action data form

### ISSUE THREAD

**Issue by zhufq00** [openai/Video-Pre-Training#33]
Hello, I would like to know the meanings of 'buttons' and 'newButtons' in the .jsonl file related to actions, as well as the significance of 'keys' and 'newKeys'.

It seems that the value of 'buttons' is always [0] or [], does [0] represent a left click of the mouse?

I haven't seen a good match for this explanation in the displayed [video ](https://[openaipublic.blob.core.windows.net](https://openaipublic.blob.core.windows.net/minecraft-rl/data/10.0/cheeky-cornflower-setter-02e496ce4abb-20220421-092639.mp4)/minecraft-rl/data/10.0/cheeky-cornflower-setter-02e496ce4abb-20220421-092639.mp4) and actions [files](https://openaipublic.blob.core.windows.net/minecraft-rl/data/10.0/cheeky-cornflower-setter-02e496ce4abb-20220421-092639.jsonl).

Thank you very much for your reply.

{
  "mouse": {
    "x": 274.0,
    "y": 338.0,
    "dx": 0.0,
    "dy": 0.0,
    "scaledX": -366.0,
    "scaledY": -22.0,
    "dwheel": 0.0,
    "buttons": [],
    "newButtons": []
  },
  "keyboard": {
    "keys": [
      "key.keyboard.a",
      "key.keyboard.s"
    ],
    "newKeys": [],
    "chars": ""
  },

**Comment by Miffyli** [comment]
`buttons` is under `mouse` key and they refer to the mouse buttons pressed. And yes, as far as I recall, mouse button "0" refers to left click. See [here](https://github.com/openai/Video-Pre-Training/blob/4ea1e8e0eddcdd5ae3cc88621a80c434f22b7f3d/run_inverse_dynamics_model.py#L114-L123)

The `buttons` and `keys` entries tell what is the state of the keyboard and mouse at that moment, i.e. what buttons are pressed down. The `newButtons` and `newKeys` tell if any new buttons were pressed down. This is useful for e.g., tracking when player wanted to open the crafting GUI, as the event happens when you press the button down the first down, but there is no point holding it down.

**Comment by zhufq00** [comment]
Thanks a lot
